// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkHuwfQWsq42mr10sLBHNwAZilr37a24',
    appId: '1:965871970667:web:591735ac9ac931f2ea042e',
    messagingSenderId: '965871970667',
    projectId: 'flowhackathon',
    authDomain: 'flowhackathon.firebaseapp.com',
    databaseURL: 'https://flowhackathon-default-rtdb.firebaseio.com',
    storageBucket: 'flowhackathon.appspot.com',
    measurementId: 'G-N3F88D4VCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMIOzNGSdRDjDpaZwyUTXc5hBV4NYh8y8',
    appId: '1:965871970667:android:34816d08cb180631ea042e',
    messagingSenderId: '965871970667',
    projectId: 'flowhackathon',
    databaseURL: 'https://flowhackathon-default-rtdb.firebaseio.com',
    storageBucket: 'flowhackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXoaJWNmFyzoWci2UoT1-f2twhEIYX-ZI',
    appId: '1:965871970667:ios:0474d48bf76726e1ea042e',
    messagingSenderId: '965871970667',
    projectId: 'flowhackathon',
    databaseURL: 'https://flowhackathon-default-rtdb.firebaseio.com',
    storageBucket: 'flowhackathon.appspot.com',
    androidClientId: '965871970667-04680287bk09c6b8k9pquvcqehgf7mp1.apps.googleusercontent.com',
    iosClientId: '965871970667-jqkrv095qctd7u86usb2f58p9roboclb.apps.googleusercontent.com',
    iosBundleId: 'com.nft.wowsports',
  );
}
